### ISSUE TITLE
Upload Assets

### ISSUE THREAD

**Issue by JoelBeasley** [froala/wysiwyg-rails#13]
Is there a way in the gem currently to define where uploads are stored? By default they are being uploaded to froala's server.

**Comment by lebart** [comment]
Hi, 

You have to specified it in your js code. All options have to be set in your application.js for instance when you initialize the editor.
 
Take a look at the docs: https://froala.com/wysiwyg-editor/docs/concepts/image-upload

    $(function() {
    $('.selector')
      .editable({
        // Set the image upload parameter.
        imageUploadParam: 'image_param',

        // Set the image upload URL.
        imageUploadURL: '/upload_image',

        // Additional upload params.
        imageUploadParams: {id: 'my_editor'}
      })
      .on('editable.imageError', function (e, editor, error) {
        // Custom error message returned from the server.
        if (error.code == 0) { ... }

        // Bad link.
        else if (error.code == 1) { ... }

        // No link in upload response.
        else if (error.code == 2) { ... }

        // Error during image upload.
        else if (error.code == 3) { ... }

        // Parsing response failed.
        else if (error.code == 4) { ... }

        // Image too text-large.
        else if (error.code == 5) { ... }

        // Invalid image type.
        else if (error.code == 6) { ... }

        // Image can be uploaded only to same domain in IE 8 and IE 9.
        else if (error.code == 7) { ... }
      });
      });

**Comment by stefanneculai** [comment]
@lebart thank you for answering this.
