### ISSUE TITLE
What I have to mention in the simple_form class so that I get to display the editor in the form ?

### ISSUE THREAD

**Issue by rasool-sb** [froala/wysiwyg-rails#14]
Hi,
   Thank you so much for lovely awesome gem, What I have to mention in the simple_form class so that I get to display the editor in the form ? for example.

    <%= simple_form_for @posts do |f| %>
        <%= f.input :username %>
        <%= f.input :error_id %>
        <%= f.input :classification, class: :??? %>
    <% end %>
Please help me..!! :)

Best Regards
SB Rasool.

**Comment by alphabetgh** [comment]
Hello, I have a similar challenge. the editor doesn't load in my blog application. How do I get it to display in my form_for form?

**Comment by lebart** [comment]
The class is your choice. For instance in your application.js

    $('.froala-editor').editable({ 'your-options-goes-here});

And then in your form:

    <%= f.text_area :content, :class => "froala-editor" %>

Take a look at the docs for more details about options. 

https://www.froala.com/wysiwyg-editor/docs

Hope this helps

**Comment by rasool-sb** [comment]
Yep.., Helps looott Thanks..!!
