### ISSUE TITLE
broken tags

### ISSUE THREAD

**Issue by ana-ines** [froala/wysiwyg-rails#16]
Hello, i'm opening this issue because i'm using this gem in my project where i am editing letters and certificates, and then exporting them to pdf.

The problem is when i put some style into the text. In the editor i see it perfect, but when i export to pdf, the pdf shows the tags brokens.. for example: "p style="text-align: left;">Señor Presidente del Colegio de Abogados:/p>p>" .

why it should be ?
thanks a lot!.

**Comment by stefanneculai** [comment]
You should check if the editor output is incorrect or your PDF converter is doing something bad. However, I don't believe that this is happening because of the editor.

**Comment by ana-ines** [comment]
Sure, the problem was the combination to pdf converter that was using the editor. 
thanks for the help !
