### ISSUE TITLE
Non-Breaking Space (Problem)

### ISSUE THREAD

**Issue by EmpireCreator** [froala/wysiwyg-rails#17]
I am creating this issue because I have been having a hard time with Froala 1.2.7's insertion of a Non-Breaking Space in HTML. The problem happens after I paste a special character (such a series of underscores, i.e. "____") next to alphabetic text (i.e, a-z) or other special characters, and then I press the space bar between the letter and the underscore. Every time, Froala insists to make that space a non-breaking space, even though only 1 space exists between the underscore and the letter (a-z).

The non-breaking space would make sense if I pressed the space bar more than once, but if I press it only once, it should not cause a non-breaking space to appear in the HTML code.

I am using a MacBook Pro with OS X 10.10.3. I am using Chrome 43.0.2357.81 (64-bit).

**Comment by stefanneculai** [comment]
It's fixed in V2.0 RC3.
