### ISSUE TITLE
Multiple editors on the same page.

### ISSUE THREAD

**Issue by pmalliak** [froala/wysiwyg-rails#18]
As the title says I have multiple editors on the same page, overall it works but I have a problem with image upload button. While on first editor the "click" to upload image opens my browser window, on the second editor nothing happens. It seems that is javascript problem I would like to know if we could have a walk-around.

Thanks in advance.

**Comment by stefanneculai** [comment]
Most probably you have some CSS that interacts with the editor and prevents it from working fine.
