### ISSUE TITLE
image upload using paperclip

### ISSUE THREAD

**Issue by roshan92** [froala/wysiwyg-rails#19]
How do upload images using paperclip gem. I find out from their website that I probably need to play around with the code below, but I can't seem to find a solution for this. Any help is appreciated.

```
// Set the image upload parameter.
imageUploadParam: 'image_param',

// Set the image upload URL.
imageUploadURL: '/upload_image',

// Additional upload params.
imageUploadParams: {id: 'my_editor'}
```

**Comment by stefanneculai** [comment]
It you have a license that includes support please contact us via our website https://www.froala.com/wysiwyg-editor/contact

**Comment by siasjustin** [comment]
Froala help center is not helpful at all.
