### ISSUE TITLE
orm adapters

### ISSUE THREAD

**Issue by asiniy** [froala/wysiwyg-rails#22]
Maintainer of the `redactor-rails` gem created an orm adapters for, i.e., [carrierwave](https://github.com/SammyLin/redactor-rails/blob/master/lib/redactor-rails/backend/carrierwave.rb)

Do you have a plans for creating adapters for paperclip, carrierwave, refile and other popular rails uploaders?

**Comment by stefanneculai** [comment]
We're always looking to improve the current plugins for the editor. Updates will definitely come in the future.

**Comment by fengzhianshang** [comment]
Chrome browser，my web application use https，now i can not upload images .
This is error message:
'http://i.froala.com/upload'. This request has been blocked; the content must be served over HTTPS

**Comment by stefanneculai** [comment]
@fengzhianshang i.froala.com supports https now and you shouldn't have the problem anymore.

**Comment by sureshy02** [comment]
Getting error as "missing content type" when i upload image

**Comment by stefanneculai** [comment]
I am closing this in favor of using: https://www.froala.com/wysiwyg-editor/docs/sdks/ruby
