### ISSUE TITLE
Installation issues with Rails 4

### ISSUE THREAD

**Issue by lorenzsell** [froala/wysiwyg-rails#24]
I've been struggling with this for a couple of days now.  I installed the gem, but Rails seems to be having a lot of trouble finding the files.  After repeated install / uninstalls, it stopped throwing errors on 

 *= require froala_editor.min.css
 *= require froala_style.min.css
 *= require font-awesome

It still can't find any of the plugin files.  I get messages like:

couldn't find file 'plugins/align.min.js' with type 'application/javascript'

And when I try to run it, it get:

Uncaught TypeError: $(...).froalaEditor is not a function

Am I missing something here?

Bundle install shows "Using wysiwyg-rails 1.2.8"

This is how I have the requires set up:

application.css.scss:
 *= require froala_editor.min.css
 *= require froala_style.min.css
 *= require font-awesome
 *= require_tree .
 *= require_self

application.js: 
//= require jquery
//= require jquery.turbolinks
//= require jquery_ujs
//= require 'typeahead.jquery'
//= require 'bloodhound'
//= require bootstrap-wysihtml5
//= require bootstrap-sprockets
//= require froala_editor.min.js
//= require turbolinks
//= require_tree .

**Comment by stefanneculai** [comment]
We have updated last week this repo to V2 RC3. The current README is for V2 RC3 and you should specify the version when initializing the editor `gem "wysiwyg-rails", "2.0.0.pre.rc.3"`.
