### ISSUE TITLE
Feature request: Font Awesome 4.5

### ISSUE THREAD

**Issue by shaunbrazier** [froala/wysiwyg-rails#30]
Would be great to upgrade to Font Awesome 4.5. My PR failed tests but not sure why: https://github.com/froala/wysiwyg-rails/pull/29

**Comment by stefanneculai** [comment]
The current requirement is `gem.add_dependency "font-awesome-rails", '~> 4.4', ">= 4.4.0.0"` which means that it should be anything higher than `4.4`. If you'd add font awesome in your GemFile and mention the version for it, then the editor will use that version.

**Comment by shaunbrazier** [comment]
@stefanneculai Thanks for the explanation.
