### ISSUE TITLE
Track Changes

### ISSUE THREAD

**Issue by WC1437** [froala/wysiwyg-rails#31]
Great product. I do not see an option to provide track changes editing (i.e., changes are marked with underline or something similar as they are typed in). Is this possible / has it been considered?

**Comment by stefanneculai** [comment]
The editor doesn't have such a feature and we have very little request for that so it's unlikely to have it implemented by ourselves. I would suggest using the editor together with ICE.JS: https://github.com/NYTimes/ice.

**Comment by WC1437** [comment]
That is a helpful reference. Thank you.
