### ISSUE TITLE
Cant change language

### ISSUE THREAD

**Issue by llermaly** [froala/wysiwyg-rails#32]
Hello, maybe I'm doing something wrong but I follow the readme and add this line to my application.js

//= require languages/ro.js

And I get this error after restarting server 

couldn't find file 'languages/ro.js'

What I'm missing?

Regards

**Comment by stefanneculai** [comment]
You should also pass the language as an option when initializing the editor. Including the JS file is not enough. https://www.froala.com/wysiwyg-editor/languages

**Comment by evpozdniakov** [comment]
How can I change it dynamically? Like you do on this page: https://www.froala.com/wysiwyg-editor/languages

**Comment by lebart** [comment]
@evpozdniakov 

I do this by adding a data attribute with the locale that I need (given by rails, like with user preference or with a link to change locale) the I retrieve this before froala initialization. The data attribute is on the text-area tag used by froala.

I'll post some exemple code if I can.
