### ISSUE TITLE
css doesn't apply

### ISSUE THREAD

**Issue by Sashkan** [froala/wysiwyg-rails#33]
Hi,

I've been trying to render the test I edited using Froala, but I got a few problems. I'm using rails-sass, so I imported the css files for froala using 
```
@import "froala_editor.min.css";
@import "froala_style.min.css";
@import "plugins/video.min.css";
@import "plugins/video.min.css";
@import "plugins/file.min.css";
@import "plugins/image.min.css";
@import "plugins/fullscreen.min.css";
@import "plugins/quick_insert.min.css";
```

The thing is, it seems like it doesn't work. Unlike all other vendors, these lines are rendered directly in my compiled css file, same format:

```
@charset "UTF-8";
/* -------------------------------------
 * Fonts
 * ------------------------------------- */
@import url("https://fonts.googleapis.com/css?family=Open+Sans:400,300,700|Montserrat:400,700|Raleway:300,400");
@import url(froala_editor.min.css);
@import url(froala_style.min.css);
@import url(plugins/video.min.css);
@import url(plugins/video.min.css);
@import url(plugins/file.min.css);
@import url(plugins/image.min.css);
@import url(plugins/fullscreen.min.css);
@import url(plugins/quick_insert.min.css);

...
```

Is that related to sass ? or did I miss something ?

Second problem is, I assume the ```fr-view``` class is the one in charge of formatting the way my text is rendered, but since I do not have the css file, I had to find an alternative, so I used the rails ```sanitize``` method. It seems to be working, however, the videos are not displayed, and the text-align is not maintained. Without ```sanitize```, I get this : 

```
<p class="futura-order centered">
   <span class="fr-video fr-dvb fr-draggable" contenteditable="false" draggable="true">
      <iframe width="560" height="315" src="https://www.youtube.com/embed/1G4isv_Fylg" frameborder="0" allowfullscreen="">
      </iframe>
   </span>
   <br>
</p>
```

With ```sanitize```, it turns into this
```
<p class="futura-order centered">
  <span class="fr-video fr-dvb fr-draggable"></span>
  <br>
</p>
```

How comes so ? Is it all related to the missing css files ?

**Comment by jbprat** [comment]
Hi Sashkan, I imagine you have overcome your issue but I would like to know how, since I have the same problem. Could you help me?

**Comment by Sashkan** [comment]
Hi @jbprat  , actually my issue came from AWS, I restricted the access to froala css and js files, and therefore had no design nor animations at all

**Comment by michaelqz** [comment]
FYI, for anyone else having the same problem, make sure you include the correct @import statements:

i.e. use: `@import "froala_editor.min";`
do not use: `@import "froala_editor.min.css";`
