### ISSUE TITLE
railties 5.0 don't work

### ISSUE THREAD

**Issue by aischylos** [froala/wysiwyg-rails#40]
Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    coffee-rails (~> 4.2) was resolved to 4.2.1, which depends on
      railties (< 5.2.x, >= 4.0.0)

    jquery-rails was resolved to 4.1.1, which depends on
      railties (>= 4.2.0)

    material_icons was resolved to 2.2.0, which depends on
      railties (>= 3.2)

    rails (~> 5.0.0) was resolved to 5.0.0, which depends on
      railties (= 5.0.0)

    sass-rails (~> 5.0) was resolved to 5.0.5, which depends on
      railties (< 6, >= 4.0.0)

    web-console was resolved to 3.3.1, which depends on
      railties (>= 5.0)

    wysiwyg-rails was resolved to 1.0.3, which depends on
      railties (< 5.0, >= 3.2)

**Comment by stefanneculai** [comment]
Are you using the Github version?

**Comment by aischylos** [comment]
No I don't think so:
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Bundler could not find compatible versions for gem "railties":

How can I use the githup version?

Thanks ahead:-)

**Comment by stefanneculai** [comment]
See http://bundler.io/git.html

**Comment by aischylos** [comment]
Sorry for the inconvenience,
how we in Germany says, the problem is sitting in front of the keyboard:-)
Have a nice Weekend and Thanks very much:-):-)

**Comment by stefanneculai** [comment]
:smile:
