### ISSUE TITLE
Not working on rails 5.0

### ISSUE THREAD

**Issue by vhilly** [froala/wysiwyg-rails#41]
I am getting the following errors during bundle install

Bundler could not find compatible versions for gem "railties":
  In snapshot (Gemfile.lock):
    railties (= 5.0.0)

  In Gemfile:
    coffee-rails (~> 4.2) was resolved to 4.2.1, which depends on
      railties (< 5.2.x, >= 4.0.0)

    devise was resolved to 4.2.0, which depends on
      railties (< 5.1, >= 4.1.0)

    font-awesome-rails was resolved to 4.6.3.1, which depends on
      railties (< 5.1, >= 3.2)

    jquery-rails was resolved to 4.1.1, which depends on
      railties (>= 4.2.0)

    rails (~> 5.0.0) was resolved to 5.0.0, which depends on
      railties (= 5.0.0)

    devise was resolved to 4.2.0, which depends on
      responders was resolved to 2.2.0, which depends on
        railties (< 5.1, >= 4.2.0)

    sass-rails (~> 5.0) was resolved to 5.0.5, which depends on
      railties (< 6, >= 4.0.0)

    web-console was resolved to 3.3.1, which depends on
      railties (>= 5.0)

    wysiwyg-rails was resolved to 1.0.3, which depends on
      railties (< 5.0, >= 3.2)

**Comment by stefanneculai** [comment]
Please follow the discussion from #40 . There will be an update here today.

**Comment by vhilly** [comment]
thanks
