### ISSUE TITLE
Wysiwyg html not rendering

### ISSUE THREAD

**Issue by mastertechrv** [froala/wysiwyg-rails#43]
**Gem File**
```
rails version 5.0.0.1
gem "wysiwyg-rails", :git => 'https://github.com/froala/wysiwyg-rails.git'
```

**Gem List to Show Verision of Gem**
```
wysiwyg-rails (2.4.0)
```

**application.scss** 
```
  *= require froala_editor.min.css
  *= require froala_style.min.css
  *= require font-awesome
```

**application.js**
```
//= require froala_editor.min.js
```

**_form.html.erb**
```
<%= f.text_area :description, :id => 'edit' %>
```

**javascript in form**
```
$(function() {
          $('#edit').froalaEditor({
            heightMin: 100,
            heightMax: 200
          })
      });
```

**Album Show Page**
```
        <div class="col-md-6">
            <div class="fr-view">
                <%= @album.description %>
            </div>
        </div>
```

My issue is when i go to view the show page the html styles do not render in the browser from the wysiwyg editor, everything in my app has its structure and there styles working, but just not the text created from the wysiwyg editor doesn't render

**for example**
This is the show page of the data from the wysiwyg 
![screen shot 2016-12-14 at 11 37 05 am](https://cloud.githubusercontent.com/assets/6068761/21190960/ae0cb936-c1f1-11e6-9745-86cb14beeb36.png)

**Note:**
The wysiwyg form renders fine. everything in the form works.

Thank you

**Comment by stefanneculai** [comment]
You would have to use `html_safe` method to mark the HTML as safe to be rendered: http://apidock.com/rails/String/html_safe
