### ISSUE TITLE
Indentation for OL/UL implemented on sub lists as well

### ISSUE THREAD

**Issue by fedesc** [froala/wysiwyg-rails#50]
if i indent text and start a list. any sublist of that list will have the same style (margin-left). anything i can do to solve this? 
![screen shot 2017-04-19 at 16 25 26](https://cloud.githubusercontent.com/assets/13513916/25182363/07650b08-251d-11e7-967f-b8ac02024db9.png)
Thanks in 

i was able to reproduce in froala demos

indent line 
start list
start sublist 
margin kept for all <li>

**Comment by stefanneculai** [comment]
@fedesc Could you please open this issue on the repo of the editor https://github.com/froala/wysiwyg-editor? Thank you.

**Comment by fedesc** [comment]
Sure np thanks!
