### ISSUE TITLE
Cannot select Text in IE11 

### ISSUE THREAD

**Issue by keferboeck** [froala/wysiwyg-rails#51]
On Version 2.5.0 as well as previous Versions I am not able to select text and click into the editor in general. It only happens on IE11. All following Edge Versions 14 and 15 work perfectly fine. I found various threads that talk about the topic, but any solution did not work. 

Here the versions in use:

Using rake 10.4.2
Using i18n 0.6.11
Using json 1.8.6
Using minitest 5.10.1
Using thread_safe 0.3.6
Using builder 3.2.3
Using erubis 2.7.0
Using rack 1.5.5
Using commonjs 0.2.7
Using concurrent-ruby 1.0.5
Using tilt 2.0.6
Using libv8 3.16.14.17 (x86_64-linux)
Using ref 2.0.0
Using execjs 2.7.0
Using thor 0.19.4
Using mime-types-data 3.2016.0521
Using arel 5.0.1.20140414130214
Using multi_json 1.12.1
Using public_suffix 2.0.5
Using bcrypt 3.1.11
Using coderay 1.1.1
Using debug_inspector 0.0.2
Using sass 3.4.23
Using bootstrap_form 2.6.0
Using breadcrumbs_on_rails 3.0.1
Using browser 2.3.0
Using cancancan 1.16.0
Using bundler 1.14.4
Using net-ssh 4.1.0
Using mini_portile2 2.1.0
Using ffi 1.9.17
Using chronic 0.10.2
Using climate_control 0.1.0
Using cocoon 1.2.9
Using coffee-script-source 1.12.2
Using deep_merge 1.1.1
Using cookie_law 0.1.2
Using i18n_data 0.7.0
Using sixarm_ruby_unaccent 1.1.1
Using unicode_utils 1.4.0
Using database_cleaner 1.5.3
Using orm_adapter 0.5.0
Using diff-lcs 1.3
Using unf_ext 0.0.7.2
Using escape_utils 1.2.1
Using fast_blank 1.0.0
Using filterrific 2.1.2
Using geocoder 1.4.3
Using gli 2.15.0
Using gmaps4rails 2.1.2
Using gritter 1.1.0
Using sexp_processor 4.8.0
Using netrc 0.11.0
Using maxminddb 0.1.12
Using mimemagic 0.3.0
Using mobileesp_converted 0.2.3
Using modernizr-rails 2.7.1
Using mysql2 0.3.21
Using newrelic_rpm 3.18.1.330
Using request_store 1.3.2
Using pr_geohash 1.0.0
Using rails_layout 1.0.34
Using rdoc 4.3.0
Using role_model 0.8.2
Using route_downcaser 1.1.5
Using rspec-core 2.14.8
Using rspec-mocks 2.14.6
Using rubyzip 1.2.1
Using websocket 1.2.4
Using settingslogic 2.0.9
Using sunspot_solr 2.2.7
Using underscore-rails 1.8.3
Using videojs_rails 4.12.15
Using will_paginate 3.1.5
Using wiselinks 1.2.1
Using faker 1.7.3
Using recaptcha 4.1.0
Using tzinfo 1.2.2
Using rsolr 1.1.2
Using sitemap_generator 5.3.1
Using rack-test 0.6.3
Using warden 1.2.7
Using rack-cache 1.7.0
Using less 2.6.0
Using sprockets 3.7.1
Using haml 4.0.7
Using therubyracer 0.12.3
Using uglifier 3.1.1
Using mime-types 3.1
Using addressable 2.5.0
Using better_errors 2.1.1
Using binding_of_caller 0.7.2
Using bootstrap-sass 3.1.1.1
Using font-awesome-sass 4.7.0
Using net-scp 1.2.1
Using nokogiri 1.7.0.1
Using childprocess 0.6.2
Using whenever 0.9.7
Using cocaine 0.5.8
Using coffee-script 2.4.1
Using money 6.8.1
Using sort_alphabetical 1.1.0
Using rspec-expectations 2.14.5
Using unf 0.1.4
Using ruby_parser 3.8.4
Using mobvious 0.3.2
Using sdoc 0.4.2
Using activesupport 4.1.12
Using sunspot 2.2.7
Using css_splitter 0.4.6
Using mail 2.6.4
Using launchy 2.4.3
Using sshkit 1.12.0
Using xpath 2.0.0
Using layzr-rails 0.1.0
Using selenium-webdriver 3.2.1
Using countries 2.0.7
Using domain_name 0.5.20170223
Using html2haml 2.1.0
Using actionview 4.1.12
Using activemodel 4.1.12
Using config 1.4.0
Using factory_girl 4.2.0
Using jbuilder 1.5.3
Using mobvious-rails 0.1.2
Using pundit 1.1.0
Using capistrano 3.1.0
Using capybara 2.12.1
Using country_select 3.0.0
Using http-cookie 1.0.3
Using actionpack 4.1.12
Using activerecord 4.1.12
Using paperclip 4.3.7
Using rest-client 2.0.1
Using less-rails 2.8.0
Using railties 4.1.12
Using actionmailer 4.1.12
Using sprockets-rails 2.3.3
Using route_translator 4.4.1
Using friendly_id 5.1.0
Using globalize 4.0.3
Using paper_trail 4.0.2
Using seed_dump 3.2.4
Using localeapp 2.1.1
Using twitter-bootstrap-rails 3.2.2
Using activerecord-session_store 1.0.0
Using bootstrap-datepicker-rails 1.6.4.1
Using bootstrap-timepicker-rails 0.1.3
Using chart-js-rails 0.0.9
Using coffee-rails 4.0.1
Using jquery-rails 3.1.4
Using responders 1.1.2
Using factory_girl_rails 4.2.1
Using fancybox2-rails 0.2.8
Using font-awesome-rails 4.7.0.1
Using haml-rails 0.9.0
Using i18n-country-translations 1.2.4
Using jquery-fileupload-rails 0.4.7
Using jquery-ui-rails 6.0.1
Using quiet_assets 1.1.0
Using rspec-rails 2.14.2
Using wysiwyg-rails 2.5.0
Using mail_form 1.6.0
Using rails 4.1.12
Using sass-rails 5.0.6
Using friendly_id-globalize 1.0.0.alpha2
Using globalize-accessors 0.1.5
Using Bootstrap-Image-Gallery-rails 1.0.1.3.1.0
Using dependent-fields-rails 0.4.2
Using devise 4.2.0
Using i18n_country_select 1.1.7
Using canonical-rails 0.1.1 from git://github.com/jumph4x/canonical-rails.git (at master@d0d558d)
Using dropzonejs-rails 0.7.3
Using gaffe 1.2.0
Using papercrop 0.3.0
Using rails4-autocomplete 1.1.1
Using sunspot_rails 2.2.7

**Comment by swarzech** [comment]
+1

**Comment by jason-hobbs** [comment]
+1

**Comment by stefanneculai** [comment]
@keferboeck @swarzech @jason-hobbs Are you able to reproduce this on our website as well: https://www.froala.com/wysiwyg-editor.

**Comment by keferboeck** [comment]
@stefanneculai - it works fine for me on https://www.froala.com/wysiwyg-editor

**Comment by jason-hobbs** [comment]
Yes, I can reproduce it on https://www.froala.com/wysiwyg-editor

**Comment by stefanneculai** [comment]
@jason-hobbs could you please make a recording? 
@keferboeck could you please send us a link where we can test?

**Comment by jason-hobbs** [comment]
Here is a recording.
[crash.zip](https://github.com/froala/wysiwyg-rails/files/1222347/crash.zip)

**Comment by stefanneculai** [comment]
@jason-hobbs it appears we cannot open the file in `.mht` format. Could you please send an avi or mp4?

**Comment by jason-hobbs** [comment]
[https://www.youtube.com/watch?v=O1c2IM_E54A](url)

**Comment by stefanneculai** [comment]
@jason-hobbs this appears to be different than the current issue and same with https://github.com/froala/wysiwyg-editor/issues/2120. We are investigating it, however we haven't been able so far to reproduce it at our end.
