### ISSUE TITLE
elem is undefined

### ISSUE THREAD

**Issue by brandoncc** [froala/wysiwyg-rails#57]
Whenever I click in the editor, I get `TypeError: elem is undefined` in my console. It doesn't seem to affect anything, but I would like to get to the bottom of this as it seems to point at a problem somewhere. We are using Rails 4.2.0.

<img width="1230" alt="image" src="https://user-images.githubusercontent.com/543973/32403493-4ad943e6-c0f8-11e7-81d3-b4620f171543.png">

**Comment by stefanneculai** [comment]
@brandoncc could you please create a place where we can replicate it? Thanks.

**Comment by brandoncc** [comment]
I'm sorry it took so long to get back to you. I finally had time to do some tests and it turns out it was coming from a jquery library that the app uses.
