### ISSUE TITLE
Licensing has been updated

### ISSUE THREAD

**Issue by seanjhulse** [froala/wysiwyg-rails#58]
The licensing has been updated on Froala's home page. You now *require* a license to use their product. They have updated their libraries to add a warning on any Froala instances being used that they must purchase a license for legal usage. Licensing was last updated November 17, 2017.

**Comment by stefanneculai** [comment]
@seanjhulse the editor always required a license. That is stated here in the ReadMe as well: https://github.com/froala/wysiwyg-rails#license.
