### ISSUE TITLE
Integration with latest version of rails_admin and file upload using carrierwave to google cloud?

### ISSUE THREAD

**Issue by StarWar** [froala/wysiwyg-rails#59]
The wiki mentioned on rails_admin page 
https://github.com/sferik/rails_admin/wiki/Froala
for integration with this gem didn't work. Also, there weren't any instructions given about integration uploading images to google cloud? Please add a readme and provide instructions to integrate with rails_admin gem.

Also It crashes when selecting all and removing formatting, I clicked several buttons in quick successions and it crashes and shows the bare textarea without froala editor?

**Comment by stefanneculai** [comment]
@StarWar the Rails Admin integration was made by [Sferik](https://github.com/sferik). Please open an issue on the [Rails Admin repo instead](https://github.com/sferik/rails_admin/).
