### ISSUE TITLE
Embed link doesn't display correctly

### ISSUE THREAD

**Issue by asancio** [froala/wysiwyg-rails#61]
How to reproduce: 
- Froala editor, click the embed.ly plugin button and use a link, for example: http://vimeo.com/18150336.
- The embed video will appear in the froala editor text area. 
- Now submit. 
- Check your view: the only thing that get displayed is a big white block.

I'm displaying raw html: <%= raw @post.body %>

System: Rails 5.1.4, Ruby 2.5

**Comment by dianaprajescu** [comment]
@asancio please let us know the OS and the browser that you are using.

**Comment by asancio** [comment]
Sorry, i forgot it: Chrome 64.0.3282.167 64 bit

**Comment by stefanneculai** [comment]
@asancio could you please include the Embedly script on the view and let us know if you still face this problem: 

```js
<!-- Include Embed.ly platform JS. -->
<script src="https://cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>
```

**Comment by asancio** [comment]
@stefanneculai yes, including the embedly script on the view fix the issue :)
Thank you.
