### ISSUE TITLE
Pasting content longer than "char counter" max results in nothing happening

### ISSUE THREAD

**Issue by brandoncc** [froala/wysiwyg-rails#62]
Our users are confused when they paste but nothing is inserted. We figured out that it happens when the pasted text is longer than the max we set for the char counter plugin. We would like to display a message to our users notifying them of what happened. It would be even better to paste the content up to the length limit, but I realize this might mess up rich formatting since the closing tags might not be pasted.

I would like to have a paste event that we can listen to that fires when the pasted content is too long.

Thanks in advance.

**Comment by stefanneculai** [comment]
@brandoncc there is actually an event which could be used for that: https://www.froala.com/wysiwyg-editor/docs/events#charCounter.exceeded.

**Comment by brandoncc** [comment]
Got it, thanks 👍

**Comment by slavik-chapelskyi** [comment]
Is there any possibility to paste text trimmed up to the max length???
