### ISSUE TITLE
Don't specify font-awesome-sass as a dependency

### ISSUE THREAD

**Issue by brendon** [froala/wysiwyg-rails#64]
I'm a business subscriber to Froala WYSIWYG:

My project is currently on Fontawesome 4 and I don't plan on changing that in the near future while I implement Froala WYSIWYG in my project. Since Fontawesome 5 is only an option at the moment, can you please remove the dependency requirement so that the `font-awesome-sass` gem doesn't get installed in my project?

This is also just a good idea anyway since Fontawesome Pro users might want to include the icons in a different way. You could add some quick documentation, or just rely on people figuring out that they need to include FA5 as you do here: https://www.froala.com/wysiwyg-editor/examples/font-awesome-5-js

**Comment by brendon** [comment]
@stefanneculai would it be possible to get this fixed and a new gem released soon as I'm getting close to deploying the editor in our app now :D

**Comment by kreintjes** [comment]
Need this as well. We are using another gem to include Font Awesome in our project (font-awesome-rails), so now we are using two gems for the same thing. We are also still using Font Awesome 4. Would be great to see this merged!

Thanks @brendon for the fix. Would have used your branch, but unfortunately it is already running a few Froala versions behind.

**Comment by brendon** [comment]
This is a good idea to fix but in the end I actually just added the froala source into my application manually. Since I'm a business subscriber I get the full source so it's good to be able to inspect the full source from the browser using this method.

**Comment by kreintjes** [comment]
Thanks for the suggestion. For now I want to keep using the wysiwyg-rails gem though. Would you mind syncing your fork with newest master of this repo, so it includes Froala 2.8.4 @brendon? I can then try out your fork/PR in my app.

**Comment by brendon** [comment]
Hi @kreintjes, have a go now :)

**Comment by RailsCod3rFuture** [comment]
I'm currently using the new "font_awesome5_rails" gem, and certain icons are missing to be clear for which. I'll list them. 1. insert video. 2. emoticons. 3. upload file. 4. undo. 5. redo 6. spell checker. Can you investigate why this issue may be occurring? 
Thanks

**Comment by brendon** [comment]
Have you also configured froala to use version 5? There's an extra setting there.

**Comment by brendon** [comment]
Here's where it is I think: https://www.froala.com/wysiwyg-editor/docs/options#iconsTemplate

**Comment by RailsCod3rFuture** [comment]
Very nice. It's working. Thanks.
