### ISSUE TITLE
Use purchased version

### ISSUE THREAD

**Issue by zenati** [froala/wysiwyg-rails#66]
Hello, how can I use the purchased froala with this gem? Because I always get "Unlicensed copy of the Froala Editor. Use it legally by purchasing a license.

Thank you.

**Comment by rylanb** [comment]
https://www.froala.com/wysiwyg-editor/pricing most likely.

**Comment by brendon** [comment]
If you've purchased froala then you need to initialise it with your product key as per the documentation.
