### ISSUE TITLE
Can not use align with image plugin

### ISSUE THREAD

**Issue by ohtasoji** [froala/wysiwyg-rails#73]
`<p><img src="http://localhost:3000/uploads/image/31/fashion_high_heel.png" style="width: 300px;" class="fr-fic fr-dib"></p><p><br><br></p>`
It is generated html.

I changed the class name from fr-fic to fr-view using the developer tool and it worked normally.
How can this work normally?

version: 2.8.5

**Comment by stefanneculai** [comment]
See https://www.froala.com/wysiwyg-editor/docs/overview#frontend.
