### ISSUE TITLE
image tui on mobile devices

### ISSUE THREAD

**Issue by brandoncc** [froala/wysiwyg-rails#75]
Image TUI supports mobile devices, but it is quite a setup process. I'm not sure how to execute this setup process while using the froala plugin. Is there a way I can use the plugin with mobile devices?

Here is the documentation:
https://github.com/nhnent/tui.image-editor/blob/master/docs/Apply-Mobile-Version.md

**Comment by stefanneculai** [comment]
We've tried to set it up, unfortunately, it doesn't look to be any quick way of doing it and it doesn't even work correctly. For now, we're going to put this on stand-by, but it will remain in our permanent attention.
