### ISSUE TITLE
missing plugins assets on rails 5.2 production environment

### ISSUE THREAD

**Issue by yllihv27** [froala/wysiwyg-rails#77]
Its working fine on dev env but when I precompile and run it in production all of plugins css cant be found 

161 B | 60 ms
-- | --
code_view.min.css | 404 | stylesheet | new | 161 B | 30 ms
colors.min.css | 404 | stylesheet | new | 161 B | 30 ms
emoticons.min.css | 404 | stylesheet | new | 161 B | 228 ms
fullscreen.min.css | 404 | stylesheet | new | 161 B | 29 ms
help.min.css | 404 | stylesheet | new | 161 B | 31 ms
line_breaker.min.css | 404 | stylesheet | new | 161 B | 25 ms
quick_insert.min.css | 404 | stylesheet | new | 161 B | 25 ms
special_characters.min.css | 404 | stylesheet | new | 161 B | 24 ms
table.min.css | 404 | stylesheet | new

**Comment by yllihv27** [comment]
Its working now ..
just changed @import 'third_party/spell_checker.min.css'  to  @import 'third_party/spell_checker.min'

**Comment by aashishpsaini** [comment]
@yllihv27 can you please share a working example of this. I'm facing the same issue.
