### ISSUE TITLE
Rails 6

### ISSUE THREAD

**Issue by jason-hobbs** [froala/wysiwyg-rails#85]
Please update for rails 6 integration.  I made a pull request and am waiting to update my apps.

**Comment by jessehanley** [comment]
After paying good amounts of $$$, I'd appreciate this simple change to be done.

**Comment by kapil2704** [comment]
Hi @jason-hobbs ,

Thanks for sending pull request. We will be reviewing Your pull request soon and get it merged.

Thanks,
Kapil Garg
Product Architect (Froala Team)

**Comment by kapil2704** [comment]
@jason-hobbs @jessehanley please check for updates in 3.0.6
