### ISSUE TITLE
Ability to install v2 in Rails 6

### ISSUE THREAD

**Issue by richardonrails** [froala/wysiwyg-rails#87]
The `railties` dependency was only relaxed in your version 3.0.6 update (which includes Editor V3). However I'd like to continue running your V2 editor on Rails 6. Any chance you can put out a 2.9.7 or 2.9.6.1 release that allows Froala Editor V2 to run on Rails 6?

**Comment by dejanmartinovic** [comment]
@richardonrails This would be possible with the next V2 release

**Comment by kapil2704** [comment]
@richardonrails This has been done with the release of 2.9.6-1. Please test and let us know.

**Comment by richardonrails** [comment]
Thanks. Is that the same version that's tagged on RubyGems as `2.9.6.pre.1`? 
https://rubygems.org/gems/wysiwyg-rails/versions/2.9.6.pre.1

**Comment by kapil2704** [comment]
Yes
